[project]
name = "profilefit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fady-Laptop", email = "flornn24@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "google>=3.0.0",
    "google-genai>=2.19.0",
    "pydantic>=2.13.4",
    "pypdf2>=3.0.1",
    "requests>=2.34.2",
]

[project.scripts]
profilefit = "profilefit:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
